pipeline:
    docker:
        image: plugins/docker
        repo: sh4d1/wat-ui
        tags: 
          - ${DRONE_COMMIT_SHA}
          - latest
        username: sh4d1
        secrets: [ docker_password ] 
    deploy:
        image: sh4d1/drone-kubernetes
        kubernetes_template: deployment.yml
        secrets: [kubernetes_server, kubernetes_cert, kubernetes_token]
